import { Category } from '../core/models/category.model';

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Latest gadgets, devices, and electronics.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Electronics',
    enabled: true,
    sortOrder: 1,
    parentId: null,
    parentName: null,
    childIds: ['cat-6', 'cat-7'],
  },
  {
    id: 'cat-2',
    name: 'Footwear',
    slug: 'footwear',
    description: 'Shoes, boots, and sandals for every occasion.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Footwear',
    enabled: true,
    sortOrder: 2,
    parentId: null,
    parentName: null,
    childIds: [],
  },
  {
    id: 'cat-3',
    name: 'Clothing',
    slug: 'clothing',
    description: 'Fashionable clothing for men and women.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Clothing',
    enabled: true,
    sortOrder: 3,
    parentId: null,
    parentName: null,
    childIds: [],
  },
  {
    id: 'cat-4',
    name: 'Sports & Outdoors',
    slug: 'sports-outdoors',
    description: 'Gear and equipment for sports and outdoor activities.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Sports',
    enabled: true,
    sortOrder: 4,
    parentId: null,
    parentName: null,
    childIds: [],
  },
  {
    id: 'cat-5',
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Everything you need for your home and kitchen.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Home+Kitchen',
    enabled: true,
    sortOrder: 5,
    parentId: null,
    parentName: null,
    childIds: [],
  },
  {
    id: 'cat-6',
    name: 'Accessories',
    slug: 'accessories',
    description: 'Electronic accessories and peripherals.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Accessories',
    enabled: true,
    sortOrder: 1,
    parentId: 'cat-1',
    parentName: 'Electronics',
    childIds: [],
  },
  {
    id: 'cat-7',
    name: 'Computers',
    slug: 'computers',
    description: 'Laptops, desktops, and computer peripherals.',
    imageUrl: 'https://via.placeholder.com/300x200?text=Computers',
    enabled: true,
    sortOrder: 2,
    parentId: 'cat-1',
    parentName: 'Electronics',
    childIds: [],
  },
];