import { Order, OrderStatus, PaymentStatus, ShippingStatus, OrderItem } from '../core/models/order.model';

export const MOCK_ORDERS: Order[] = [
  {
    id: '1001',
    orderNumber: 'ORD-2024-0001',
    userId: 'user-1',
    customerName: 'John Doe',
    email: 'john@example.com',
    phone: '+1 555-0101',
    telegramUsername: '@johndoe',
    address: '123 Main St, New York, NY 10001, US',
    note: '',
    items: [
      {
        id: 'oi-1',
        orderId: '1001',
        productId: '1',
        productName: 'Custom T-Shirt Premium',
        productSlug: 'custom-tshirt-premium',
        productImage: 'https://via.placeholder.com/100x100?text=TShirt',
        unitPrice: 29.99,
        quantity: 50,
        subtotal: 1499.50,
        selectedSize: 'M',
        selectedColor: 'Navy Blue',
        selectedDecorationMethod: 'Screen Print',
        selectedPrintPosition: 'Front Left Chest',
        selectedPrintColors: [{ colorId: 'c1', colorName: 'White', colorHex: '#FFFFFF' }],
        uploadedDesignFiles: [
          { id: 'df-1', orderItemId: 'oi-1', fileName: 'logo.png', fileUrl: '/uploads/logo.png', fileType: 'image/png', fileSize: 245000, uploadedAt: '2024-05-01T09:00:00Z' },
        ],
        customizationFee: 2.50,
        productionTime: 7,
      },
      {
        id: 'oi-2',
        orderId: '1001',
        productId: '3',
        productName: 'Running Shoes Ultra',
        productSlug: 'running-shoes-ultra',
        productImage: 'https://via.placeholder.com/100x100?text=Shoes',
        unitPrice: 99.99,
        quantity: 2,
        subtotal: 199.98,
        selectedSize: 'US 10',
        selectedColor: 'Black',
        selectedDecorationMethod: null,
        selectedPrintPosition: null,
        selectedPrintColors: [],
        uploadedDesignFiles: [],
        customizationFee: 0,
        productionTime: null,
      },
    ] as OrderItem[],
    subtotal: 1699.48,
    discount: 50.00,
    deliveryFee: 0,
    customizationFeeTotal: 125.00,
    tax: 0,
    grandTotal: 1774.48,
    totalItems: 52,
    status: OrderStatus.DELIVERED,
    paymentStatus: PaymentStatus.PAID,
    shippingStatus: ShippingStatus.DELIVERED,
    paymentMethodId: 'pay-cc',
    paymentMethodName: 'Credit Card',
    paymentTransactionId: 'txn-abc123',
    paymentProofUrl: null,
    shippingMethodId: 'sm-1',
    shippingMethodName: 'Standard Shipping',
    shippingZoneId: 'sz-1',
    shippingZoneName: 'Domestic',
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-05-03T15:00:00Z',
  },
  {
    id: '1002',
    orderNumber: 'ORD-2024-0002',
    userId: 'user-1',
    customerName: 'John Doe',
    email: 'john@example.com',
    phone: '+1 555-0101',
    telegramUsername: '@johndoe',
    address: '123 Main St, New York, NY 10001, US',
    note: 'Leave at the door.',
    items: [
      {
        id: 'oi-3',
        orderId: '1002',
        productId: '9',
        productName: 'Coffee Maker Deluxe',
        productSlug: 'coffee-maker-deluxe',
        productImage: 'https://via.placeholder.com/100x100?text=Coffee+Maker',
        unitPrice: 119.99,
        quantity: 1,
        subtotal: 119.99,
        selectedSize: null,
        selectedColor: 'Silver',
        selectedDecorationMethod: null,
        selectedPrintPosition: null,
        selectedPrintColors: [],
        uploadedDesignFiles: [],
        customizationFee: 0,
        productionTime: null,
      },
    ] as OrderItem[],
    subtotal: 119.99,
    discount: 0,
    deliveryFee: 9.99,
    customizationFeeTotal: 0,
    tax: 0,
    grandTotal: 129.98,
    totalItems: 1,
    status: OrderStatus.PROCESSING,
    paymentStatus: PaymentStatus.PAID,
    shippingStatus: ShippingStatus.PREPARING,
    paymentMethodId: 'pay-pp',
    paymentMethodName: 'PayPal',
    paymentTransactionId: 'txn-paypal-456',
    paymentProofUrl: null,
    shippingMethodId: 'sm-2',
    shippingMethodName: 'Express Shipping',
    shippingZoneId: 'sz-3',
    shippingZoneName: 'Regional',
    createdAt: '2024-05-20T14:00:00Z',
    updatedAt: '2024-05-21T09:00:00Z',
  },
  {
    id: '1003',
    orderNumber: 'ORD-2024-0003',
    userId: 'user-2',
    customerName: 'Jane Smith',
    email: 'jane@acme.com',
    phone: '+1 555-0102',
    telegramUsername: '@janesmith',
    address: '456 Oak Ave, Suite 100, Los Angeles, CA 90001, US',
    note: '',
    items: [
      {
        id: 'oi-4',
        orderId: '1003',
        productId: '2',
        productName: 'Smart Watch Pro',
        productSlug: 'smart-watch-pro',
        productImage: 'https://via.placeholder.com/100x100?text=Watch',
        unitPrice: 449.99,
        quantity: 1,
        subtotal: 449.99,
        selectedSize: null,
        selectedColor: 'Space Gray',
        selectedDecorationMethod: null,
        selectedPrintPosition: null,
        selectedPrintColors: [],
        uploadedDesignFiles: [],
        customizationFee: 0,
        productionTime: null,
      },
    ] as OrderItem[],
    subtotal: 449.99,
    discount: 45.00,
    deliveryFee: 0,
    customizationFeeTotal: 0,
    tax: 0,
    grandTotal: 404.99,
    totalItems: 1,
    status: OrderStatus.SHIPPED,
    paymentStatus: PaymentStatus.PAID,
    shippingStatus: ShippingStatus.IN_TRANSIT,
    paymentMethodId: 'pay-cc',
    paymentMethodName: 'Credit Card',
    paymentTransactionId: 'txn-xyz789',
    paymentProofUrl: null,
    shippingMethodId: 'sm-1',
    shippingMethodName: 'Standard Shipping',
    shippingZoneId: 'sz-1',
    shippingZoneName: 'Domestic',
    createdAt: '2024-05-15T08:00:00Z',
    updatedAt: '2024-05-17T11:00:00Z',
  },
  {
    id: '1004',
    orderNumber: 'ORD-2024-0004',
    userId: 'user-1',
    customerName: 'John Doe',
    email: 'john@example.com',
    phone: '+1 555-0101',
    telegramUsername: '@johndoe',
    address: '123 Main St, New York, NY 10001, US',
    note: 'Rush order please.',
    items: [
      {
        id: 'oi-5',
        orderId: '1004',
        productId: '5',
        productName: 'Custom Hoodie Classic',
        productSlug: 'custom-hoodie-classic',
        productImage: 'https://via.placeholder.com/100x100?text=Hoodie',
        unitPrice: 49.99,
        quantity: 25,
        subtotal: 1249.75,
        selectedSize: 'L',
        selectedColor: 'Charcoal',
        selectedDecorationMethod: 'Embroidery',
        selectedPrintPosition: 'Left Chest',
        selectedPrintColors: [{ colorId: 'c2', colorName: 'Gold', colorHex: '#FFD700' }],
        uploadedDesignFiles: [
          { id: 'df-2', orderItemId: 'oi-5', fileName: 'company-logo.svg', fileUrl: '/uploads/company-logo.svg', fileType: 'image/svg+xml', fileSize: 12000, uploadedAt: '2024-06-01T10:00:00Z' },
        ],
        customizationFee: 5.00,
        productionTime: 10,
      },
    ] as OrderItem[],
    subtotal: 1249.75,
    discount: 0,
    deliveryFee: 15.00,
    customizationFeeTotal: 125.00,
    tax: 0,
    grandTotal: 1389.75,
    totalItems: 25,
    status: OrderStatus.PENDING,
    paymentStatus: PaymentStatus.PENDING,
    shippingStatus: ShippingStatus.NOT_SHIPPED,
    paymentMethodId: 'pay-cod',
    paymentMethodName: 'Cash on Delivery (COD)',
    paymentTransactionId: null,
    paymentProofUrl: null,
    shippingMethodId: 'sm-2',
    shippingMethodName: 'Express Shipping',
    shippingZoneId: 'sz-1',
    shippingZoneName: 'Domestic',
    createdAt: '2024-06-01T12:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
];
