import { ShippingMethod } from '../core/models/shipping.model';

export const MOCK_SHIPPING_METHODS: ShippingMethod[] = [
  {
    id: 'sm-1',
    name: 'Phnom Penh Delivery',
    code: 'PHNOM_PENH',
    description: 'Standard delivery within Phnom Penh city limits.',
    baseFee: 0,
    isActive: true,
    estimatedDeliveryTime: '1-2 days',
    sortOrder: 1,
  },
  {
    id: 'sm-2',
    name: 'Province Delivery',
    code: 'PROVINCE',
    description: 'Delivery to provinces outside Phnom Penh.',
    baseFee: 2,
    isActive: true,
    estimatedDeliveryTime: '3-5 days',
    sortOrder: 2,
  },
  {
    id: 'sm-3',
    name: 'J&T Express',
    code: 'JT_EXPRESS',
    description: 'Fast courier service via J&T Express.',
    baseFee: 3,
    isActive: true,
    estimatedDeliveryTime: '2-4 days',
    sortOrder: 3,
  },
  {
    id: 'sm-4',
    name: 'VET Express',
    code: 'VET_EXPRESS',
    description: 'Reliable courier service via VET Express.',
    baseFee: 3,
    isActive: true,
    estimatedDeliveryTime: '2-4 days',
    sortOrder: 4,
  },
  {
    id: 'sm-5',
    name: 'International Shipping',
    code: 'INTERNATIONAL',
    description: 'Shipping to international destinations.',
    baseFee: 15,
    isActive: false,
    estimatedDeliveryTime: '7-14 days',
    sortOrder: 5,
  },
];
