import { Review, ReviewStatus } from '../core/models/review.model';

export const MOCK_REVIEWS: Review[] = [
  {
    id: '1',
    productId: '1',
    productName: 'Wireless Bluetooth Headphones',
    userId: 'user-1',
    userName: 'Alex Johnson',
    rating: 5,
    title: 'Amazing sound quality!',
    comment: 'These headphones are incredible. The noise cancellation works perfectly and the battery lasts all day.',
    images: [],
    verifiedPurchase: true,
    helpfulCount: 24,
    status: ReviewStatus.APPROVED,
    createdAt: '2024-05-10T14:30:00Z',
    updatedAt: '2024-05-10T14:30:00Z',
  },
  {
    id: '2',
    productId: '1',
    productName: 'Wireless Bluetooth Headphones',
    userId: 'user-2',
    userName: 'Sarah Williams',
    rating: 4,
    title: 'Great but pricey',
    comment: 'Love the sound and comfort. A bit expensive but worth it.',
    images: [],
    verifiedPurchase: true,
    helpfulCount: 8,
    status: ReviewStatus.APPROVED,
    createdAt: '2024-05-15T09:00:00Z',
    updatedAt: '2024-05-15T09:00:00Z',
  },
  {
    id: '3',
    productId: '3',
    productName: 'Running Shoes Ultra',
    userId: 'user-3',
    userName: 'Mike Chen',
    rating: 5,
    title: 'Best running shoes ever!',
    comment: 'Extremely comfortable and lightweight. Perfect for daily runs.',
    images: [],
    verifiedPurchase: true,
    helpfulCount: 15,
    status: ReviewStatus.APPROVED,
    createdAt: '2024-04-20T11:00:00Z',
    updatedAt: '2024-04-20T11:00:00Z',
  },
];