import { Product, ProductStatus } from '../core/models/product.model';
import { Category } from '../core/models/category.model';
import { Banner, BannerPosition } from '../core/models/banner.model';
import { Review, ReviewStatus } from '../core/models/review.model';
import { Coupon, CouponDiscountType } from '../core/models/coupon.model';
import { PaymentMethod, PaymentMethodType } from '../core/models/payment-method.model';

// ============ MOCK PRODUCTS ============
export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Wireless Bluetooth Headphones',
    slug: 'wireless-bluetooth-headphones',
    description: 'High-quality wireless headphones with active noise cancellation and 30-hour battery life.',
    price: 299.99,
    salePrice: 249.99,
    stockQuantity: 50,
    sku: 'WBH-001-BLK',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Headphones',
    images: [
      'https://via.placeholder.com/800x800?text=Headphones+1',
      'https://via.placeholder.com/800x800?text=Headphones+2',
    ],
    featured: true,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '2',
    name: 'Smart Watch Pro',
    slug: 'smart-watch-pro',
    description: 'Advanced smartwatch with health monitoring, GPS, and 7-day battery life.',
    price: 449.99,
    salePrice: null,
    stockQuantity: 25,
    sku: 'SWP-002-SLV',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Smart+Watch',
    images: [
      'https://via.placeholder.com/800x800?text=Watch+1',
    ],
    featured: true,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-02-20T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '3',
    name: 'Running Shoes Ultra',
    slug: 'running-shoes-ultra',
    description: 'Lightweight running shoes with responsive cushioning and breathable mesh upper.',
    price: 129.99,
    salePrice: 99.99,
    stockQuantity: 100,
    sku: 'RSU-003-WHT',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Shoes',
    images: [
      'https://via.placeholder.com/800x800?text=Shoes+1',
      'https://via.placeholder.com/800x800?text=Shoes+2',
    ],
    featured: true,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-2',
    categoryName: 'Footwear',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '4',
    name: 'Classic Leather Jacket',
    slug: 'classic-leather-jacket',
    description: 'Premium genuine leather jacket with timeless design and soft lining.',
    price: 399.99,
    salePrice: null,
    stockQuantity: 15,
    sku: 'CLJ-004-BRN',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Jacket',
    images: [
      'https://via.placeholder.com/800x800?text=Jacket+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-01-05T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '5',
    name: 'Laptop Stand Adjustable',
    slug: 'laptop-stand-adjustable',
    description: 'Ergonomic aluminum laptop stand with 6 height adjustments and heat dissipation.',
    price: 79.99,
    salePrice: 59.99,
    stockQuantity: 200,
    sku: 'LSA-005-SLV',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Laptop+Stand',
    images: [
      'https://via.placeholder.com/800x800?text=Stand+1',
      'https://via.placeholder.com/800x800?text=Stand+2',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-04-12T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '6',
    name: 'Organic Cotton T-Shirt',
    slug: 'organic-cotton-tshirt',
    description: 'Sustainable 100% organic cotton t-shirt available in multiple colors.',
    price: 34.99,
    salePrice: null,
    stockQuantity: 500,
    sku: 'OCT-006-GRN',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=T-Shirt',
    images: [
      'https://via.placeholder.com/800x800?text=Shirt+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-05-01T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '7',
    name: 'Portable Bluetooth Speaker',
    slug: 'portable-bluetooth-speaker',
    description: 'Waterproof portable speaker with 360° sound and 12-hour playtime.',
    price: 89.99,
    salePrice: 69.99,
    stockQuantity: 75,
    sku: 'PBS-007-BLK',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Speaker',
    images: [
      'https://via.placeholder.com/800x800?text=Speaker+1',
    ],
    featured: true,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-03-25T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '8',
    name: 'Yoga Mat Premium',
    slug: 'yoga-mat-premium',
    description: 'Extra thick non-slip yoga mat with carrying strap and alignment markers.',
    price: 54.99,
    salePrice: null,
    stockQuantity: 150,
    sku: 'YMP-008-PRP',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Yoga+Mat',
    images: [
      'https://via.placeholder.com/800x800?text=Yoga+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-4',
    categoryName: 'Sports & Outdoors',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-04-01T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '9',
    name: 'Coffee Maker Deluxe',
    slug: 'coffee-maker-deluxe',
    description: '12-cup programmable coffee maker with thermal carafe and built-in grinder.',
    price: 149.99,
    salePrice: 119.99,
    stockQuantity: 40,
    sku: 'CMD-009-GLD',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Coffee+Maker',
    images: [
      'https://via.placeholder.com/800x800?text=Coffee+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-5',
    categoryName: 'Home & Kitchen',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-01-28T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '10',
    name: 'Winter Parka',
    slug: 'winter-parka',
    description: 'Insulated winter parka with faux fur hood and waterproof exterior.',
    price: 249.99,
    salePrice: 199.99,
    stockQuantity: 60,
    sku: 'WP-010-BLK',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Parka',
    images: [
      'https://via.placeholder.com/800x800?text=Parka+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-02-14T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '11',
    name: 'USB-C Hub 7-in-1',
    slug: 'usb-c-hub-7in1',
    description: 'Compact USB-C hub with HDMI, USB 3.0, SD card, and PD charging.',
    price: 49.99,
    salePrice: null,
    stockQuantity: 300,
    sku: 'UCH-011-SLV',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=USB+Hub',
    images: [
      'https://via.placeholder.com/800x800?text=Hub+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-05-15T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '12',
    name: 'Stainless Steel Water Bottle',
    slug: 'stainless-steel-water-bottle',
    description: 'Double-wall vacuum insulated water bottle keeps drinks cold 24 hours.',
    price: 29.99,
    salePrice: null,
    stockQuantity: 400,
    sku: 'SSB-012-STE',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Bottle',
    images: [
      'https://via.placeholder.com/800x800?text=Bottle+1',
    ],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-4',
    categoryName: 'Sports & Outdoors',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-04-20T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '13',
    name: 'Mechanical Keyboard RGB',
    slug: 'mechanical-keyboard-rgb',
    description: 'Full-size mechanical keyboard with hot-swappable switches and per-key RGB lighting.',
    price: 159.99,
    salePrice: 129.99,
    stockQuantity: 80,
    sku: 'MKR-013-BLK',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Keyboard',
    images: ['https://via.placeholder.com/800x800?text=Keyboard+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-05-20T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '14',
    name: 'Denim Jacket Classic',
    slug: 'denim-jacket-classic',
    description: 'Timeless denim jacket with button closure and chest pockets.',
    price: 89.99,
    salePrice: null,
    stockQuantity: 45,
    sku: 'DJC-014-BLU',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Denim+Jacket',
    images: ['https://via.placeholder.com/800x800?text=Denim+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '15',
    name: 'Wireless Mouse Ergonomic',
    slug: 'wireless-mouse-ergonomic',
    description: 'Ergonomic wireless mouse with silent clicks and adjustable DPI.',
    price: 49.99,
    salePrice: 39.99,
    stockQuantity: 120,
    sku: 'WME-015-GRY',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Mouse',
    images: ['https://via.placeholder.com/800x800?text=Mouse+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-06-01T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '16',
    name: 'Canvas Backpack',
    slug: 'canvas-backpack',
    description: 'Durable canvas backpack with padded laptop compartment and multiple pockets.',
    price: 69.99,
    salePrice: null,
    stockQuantity: 90,
    sku: 'CB-016-BRN',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Backpack',
    images: ['https://via.placeholder.com/800x800?text=Backpack+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-02-10T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '17',
    name: 'Sunglasses Polarized',
    slug: 'sunglasses-polarized',
    description: 'Premium polarized sunglasses with UV400 protection and lightweight frame.',
    price: 119.99,
    salePrice: 89.99,
    stockQuantity: 65,
    sku: 'SP-017-BLK',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Sunglasses',
    images: ['https://via.placeholder.com/800x800?text=Sunglasses+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-04-05T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '18',
    name: 'Fitness Tracker Band',
    slug: 'fitness-tracker-band',
    description: 'Slim fitness tracker with heart rate monitor, sleep tracking, and waterproof design.',
    price: 79.99,
    salePrice: null,
    stockQuantity: 110,
    sku: 'FTB-018-BLK',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Fitness+Band',
    images: ['https://via.placeholder.com/800x800?text=Fitness+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-1',
    categoryName: 'Electronics',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-05-30T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '19',
    name: 'Leather Wallet RFID',
    slug: 'leather-wallet-rfid',
    description: 'Slim genuine leather wallet with RFID blocking and multiple card slots.',
    price: 44.99,
    salePrice: 34.99,
    stockQuantity: 200,
    sku: 'LWR-019-BRN',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Wallet',
    images: ['https://via.placeholder.com/800x800?text=Wallet+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-3',
    categoryName: 'Clothing',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-06-01T12:00:00Z',
  },
  {
    id: '20',
    name: 'Desk Lamp LED',
    slug: 'desk-lamp-led',
    description: 'Adjustable LED desk lamp with touch control, USB charging, and 5 brightness levels.',
    price: 59.99,
    salePrice: null,
    stockQuantity: 85,
    sku: 'DL-020-WHT',
    thumbnailUrl: 'https://via.placeholder.com/400x400?text=Desk+Lamp',
    images: ['https://via.placeholder.com/800x800?text=Lamp+1'],
    featured: false,
    enabled: true,
    status: ProductStatus.ACTIVE,
    categoryId: 'cat-5',
    categoryName: 'Home & Kitchen',
    allowReview: true,
    allowCoupon: true,
    allowCart: true,
    allowCheckout: true,
    createdAt: '2024-06-10T10:00:00Z',
    updatedAt: '2024-06-10T12:00:00Z',
  },
];