import { Banner, BannerPosition } from '../core/models/banner.model';

export const MOCK_BANNERS: Banner[] = [
  {
    id: '1',
    title: 'Summer Sale',
    subtitle: 'Up to 50% off on selected items',
    imageUrl: 'https://via.placeholder.com/1200x400?text=Summer+Sale',
    linkUrl: '/products',
    linkText: 'Shop Now',
    position: BannerPosition.HERO,
    enabled: true,
    sortOrder: 1,
    startsAt: null,
    endsAt: '2024-08-31T23:59:59Z',
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: '2',
    title: 'New Arrivals',
    subtitle: 'Check out our latest collection',
    imageUrl: 'https://via.placeholder.com/600x400?text=New+Arrivals',
    linkUrl: '/products',
    linkText: 'Explore',
    position: BannerPosition.PROMO,
    enabled: true,
    sortOrder: 2,
    startsAt: null,
    endsAt: null,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
  {
    id: '3',
    title: 'Free Shipping',
    subtitle: 'On orders over $50',
    imageUrl: 'https://via.placeholder.com/300x200?text=Free+Shipping',
    linkUrl: '/products',
    linkText: 'Learn More',
    position: BannerPosition.SIDEBAR,
    enabled: true,
    sortOrder: 3,
    startsAt: null,
    endsAt: null,
    createdAt: '2024-06-01T00:00:00Z',
    updatedAt: '2024-06-01T00:00:00Z',
  },
];