import { CartItem } from '../core/models/cart.model';

export const MOCK_CART_ITEMS: CartItem[] = [
  {
    id: 'cart-1',
    productId: '1',
    productName: 'Wireless Bluetooth Headphones',
    productSlug: 'wireless-bluetooth-headphones',
    productImage: 'https://via.placeholder.com/400x400?text=Headphones',
    unitPrice: 249.99,
    quantity: 1,
    subtotal: 249.99,
    selectedSize: null,
    selectedColor: 'Black',
    selectedDecorationMethod: 'Screen Printing',
    selectedPrintPosition: 'Front',
    uploadedDesignFiles: [
      { position: 'front', fileName: 'logo.png', fileType: 'image/png', fileSize: 45000 },
    ],
    selectedPrintColors: [
      { colorId: 'black', colorName: 'Black', colorHex: '#222222' },
    ],
    customizationFee: 3,
    productionTime: 5,
    maxQuantity: 50,
    stockQuantity: 50,
    salePrice: 249.99,
  },
  {
    id: 'cart-2',
    productId: '3',
    productName: 'Running Shoes Ultra',
    productSlug: 'running-shoes-ultra',
    productImage: 'https://via.placeholder.com/400x400?text=Shoes',
    unitPrice: 99.99,
    quantity: 2,
    subtotal: 199.98,
    selectedSize: 'US 10',
    selectedColor: null,
    selectedDecorationMethod: null,
    selectedPrintPosition: null,
    uploadedDesignFiles: [],
    selectedPrintColors: [],
    customizationFee: 0,
    productionTime: null,
    maxQuantity: 100,
    stockQuantity: 100,
    salePrice: 99.99,
  },
];
